    # This file is autogenerated by the flake.nix file, do not edit source "https://rubygems.org"
    source "https://rubygems.org"
    # Gems dependencies to be installed
    gem "wifi-wand", "~> 2.18.0"
#   
